name: Run action

on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: install R
      run: apt-get update && apt-get install r-base
